services:
  - type: web
    name: stk-shop-api
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    healthCheckPath: /api/test-db
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        scope: run
      - key: DB_USER
        scope: run
      - key: DB_PASSWORD
        scope: run
      - key: DB_NAME
        scope: run
      - key: DB_PORT
        scope: run
      - key: JWT_SECRET
        scope: run
      - key: ADMIN_EMAIL
        scope: run
      - key: ADMIN_PASSWORD
        scope: run
      - key: PORT
        value: 5000
